Notch/Controllers/ProductController.cs
using System.Web.Mvc;
using Notch.Infrastructure.Business;

namespace Notch.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Product
        public ActionResult Index()
        {
            using (var productDm = Factory.GetService<IProductDM>(RequestContext))
            {
                var products = productDm.GetAll();

                return View(products);
            }
        }
    }
}

Notch/Controllers/TrackController.cs
namespace Notch.Controllers
{
    using System.Web.Mvc;
    using Notch.Domain;
    using Notch.Infrastructure.Business;

    public class TrackController : BaseController
    {
        public ActionResult Index()
        {
            using (var trackDM = this.Factory.GetService<ITrackDM>(this.RequestContext))
            {
                var tracks = trackDM.GetTracks();

                return View(tracks);
            }
        }

        public ActionResult AddOrUpdate(Track track)
        {
            using (var trackDm = this.Factory.GetService<ITrackDM>(this.RequestContext))
            {
                if (ModelState.IsValid)
                {
                    if (track.Id != 0)
                    {
                        trackDm.Update(track);

                        return RedirectToAction("Index");
                    }

                    trackDm.AddTrack(track);

                    return RedirectToAction("Index");
                }

                return PartialView("_CreateEditTrack", track);
            }
        }

        public ActionResult DeleteTrack(int id)
        {
            using (var trackDm = this.Factory.GetService<ITrackDM>(this.RequestContext))
            {
                trackDm.DeleteTrack(id);

                return RedirectToAction("Index");
            }
        }
    }
}

Notch/Controllers/TrackKnockoutController.cs
namespace Notch.Controllers
{
    using System.Web.Mvc;
    using Notch.Infrastructure.Business;

    public class TrackKnockoutController : BaseController
    {
        public ActionResult Index()
        {
            using (var trackDM = this.Factory.GetService<ITrackDM>(this.RequestContext))
            {
                var tracks = trackDM.GetTracks();

                return View(tracks);
            }
        }
    }
}

Notch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/main")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("TracksMVC", "Index", "Track")</li>
                    <li>@Html.ActionLink("TracksKnockout", "Index", "TrackKnockout")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>